services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: my-nest-api-dev
    environment:
      - NODE_ENV=dev
      - API_KEY=GEMINI_API_KEY
    ports:
      - "3100:3100"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -lc "npm ci --ignore-scripts && npx node-gyp rebuild && npm run start:dev"
    restart: unless-stopped